// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIP_XyaLCUdJ9nlrm7S3ckxROkataKWa4',
    appId: '1:510047851295:web:834c56509955c88fb8162a',
    messagingSenderId: '510047851295',
    projectId: 'login-751c1',
    authDomain: 'login-751c1.firebaseapp.com',
    storageBucket: 'login-751c1.appspot.com',
    measurementId: 'G-EB5ND494RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa4F1zHPpP03ik-6iHimOJnRQzsXfCSsM',
    appId: '1:510047851295:android:53032fbcf11fd758b8162a',
    messagingSenderId: '510047851295',
    projectId: 'login-751c1',
    storageBucket: 'login-751c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKnVNMruSY3RQoMjaW7MleV9VoiK8tHIE',
    appId: '1:510047851295:ios:c7d792054df30693b8162a',
    messagingSenderId: '510047851295',
    projectId: 'login-751c1',
    storageBucket: 'login-751c1.appspot.com',
    iosBundleId: 'com.example.simpleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKnVNMruSY3RQoMjaW7MleV9VoiK8tHIE',
    appId: '1:510047851295:ios:86c264618cb32822b8162a',
    messagingSenderId: '510047851295',
    projectId: 'login-751c1',
    storageBucket: 'login-751c1.appspot.com',
    iosBundleId: 'com.example.simpleLogin.RunnerTests',
  );
}
